Repository APPSCHOOL2-Android/FinalProject-PetPal, pull requests merged in 2023-09, with the labels that each got.

#7 [#3] feat : 채팅 목록, 채팅방, 산책 메이트 요청 화면 UI 작성
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/ChatFragment.kt
  app/src/main/java/com/petpal/mungmate/model/ChatRoom.kt
  app/src/main/java/com/petpal/mungmate/model/Message.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/ChatFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/ChatRoomFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/ChatRoomListAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/MessageListAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/WalkMateRequestFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/FAQFragment.kt
  app/src/main/res/drawable/arrow_back_24px.xml
  app/src/main/res/drawable/arrow_upward_24px.xml
  app/src/main/res/drawable/background_receive_message.xml
  app/src/main/res/drawable/background_send_message.xml
  app/src/main/res/drawable/background_unread_message_count.xml
  app/src/main/res/drawable/close_24px.xml
  app/src/main/res/drawable/default_profile_image.jpg
  app/src/main/res/drawable/done_24px.xml
  app/src/main/res/drawable/event_24px.xml
  app/src/main/res/drawable/location_on_24px.xml
  app/src/main/res/drawable/person_off_24px.xml
  app/src/main/res/drawable/schedule_24px.xml
  app/src/main/res/drawable/send_24px.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_f_a_q.xml
  app/src/main/res/layout/fragment_walk_mate_request.xml
  app/src/main/res/layout/row_chat_room.xml
  app/src/main/res/layout/row_receive_message.xml
  app/src/main/res/layout/row_send_message.xml
  app/src/main/res/layout/row_walk_mate_matching_message.xml
  app/src/main/res/layout/row_walk_mate_request_message.xml
  app/src/main/res/menu/menu_chat_room.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
Labels: feature, ui

#8 [#2] feat : [수정완료]커뮤니티 글 목록, 상세, 작성, 편집 UI 작성
  .idea/kotlinc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/community/CommunityDetailCommentAdapter.kt
  app/src/main/java/com/petpal/mungmate/community/CommunityDetailModifyFragment.kt
  app/src/main/java/com/petpal/mungmate/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/community/CommunityWritingFragment.kt
  app/src/main/res/anim/from_bottom.xml
  app/src/main/res/anim/from_left.xml
  app/src/main/res/anim/from_right.xml
  app/src/main/res/anim/from_top.xml
  app/src/main/res/anim/to_left.xml
  app/src/main/res/anim/to_right.xml
  app/src/main/res/drawable-v24/launcher_foreground.xml
  app/src/main/res/drawable/add.xml
  app/src/main/res/drawable/comment.xml
  app/src/main/res/drawable/delete.xml
  app/src/main/res/drawable/edit.xml
  app/src/main/res/drawable/favorite_border.xml
  app/src/main/res/drawable/image.xml
  app/src/main/res/drawable/keyboard_arrow_right.xml
  app/src/main/res/drawable/launcher_background.xml
  app/src/main/res/drawable/more_vert.xml
  app/src/main/res/layout/community_category_list.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_community_detail_modify.xml
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/fragment_community_writing.xml
  app/src/main/res/layout/row_community.xml
  app/src/main/res/layout/row_community_comment.xml
  app/src/main/res/menu/community_post_detail_author.xml
  app/src/main/res/menu/community_post_detail_comment.xml
  app/src/main/res/menu/community_post_detail_user.xml
  app/src/main/res/menu/community_post_modify.xml
  app/src/main/res/menu/community_writing_menu.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature, ui

#12 [#9] feat : 앱 로고 splash 화면 완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/community/CommunityDetailCommentAdapter.kt
  app/src/main/res/drawable/petpal_splash_animation.gif
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/row_community.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_back.png
  app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_fore.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round_adaptive_back.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round_adaptive_fore.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_back.png
  app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_fore.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round_adaptive_back.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round_adaptive_fore.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_back.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_fore.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round_adaptive_back.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round_adaptive_fore.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_back.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_fore.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round_adaptive_back.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round_adaptive_fore.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_back.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_fore.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round_adaptive_back.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round_adaptive_fore.png
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, ui

#15 [#2]design : 커뮤니티 카테고리 chip custom
  app/src/main/java/com/petpal/mungmate/MainFragment.kt
  app/src/main/res/color/select_checked_chip.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: ui

#17 [#16]bottomNavigation UI 변경
  app/src/main/res/color/slecte_checked_bottom_navigation.xml
  app/src/main/res/color/slecte_checked_chip.xml
  app/src/main/res/color/slecte_checked_chip_text.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: ui

#22 [#2]feat : lottie, skeletonlayout 추가, 카테고리 사이드 시트로 변경 #2
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailCommentAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailModifyFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunitySearchFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityWritingFragment.kt
  app/src/main/res/drawable/category.xml
  app/src/main/res/drawable/dehaze.xml
  app/src/main/res/drawable/search.xml
  app/src/main/res/layout/community_side_sheet_behavior.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_community_detail_modify.xml
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/fragment_community_search.xml
  app/src/main/res/layout/fragment_community_writing.xml
  app/src/main/res/layout/row_community.xml
  app/src/main/res/layout/row_community_comment.xml
  app/src/main/res/menu/community_category_menu.xml
  app/src/main/res/navigation/community.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/raw/favorite.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, ui

#29 Gayeon/25 mypage edit
  app/src/main/java/com/petpal/mungmate/MyPageFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/BlockUserRecyclerAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/ManageBlockFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/MatchHistoryFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/MatchHistoryRecyclerAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/walkhistory/WalkHistoryDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walkhistory/WalkHistoryFragment.kt
  app/src/main/res/layout/fragment_manage_block.xml
  app/src/main/res/layout/fragment_match_history.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_walk_history.xml
  app/src/main/res/layout/fragment_walk_history_detail.xml
  app/src/main/res/layout/row_block_user.xml
  app/src/main/res/layout/row_match_history.xml
  app/src/main/res/navigation/community.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/navigation/mypage.xml
Labels: feature, ui

#27 [#6] feat : FAQ, 1:1문의, 신고하기 화면 UI 작성, 채팅방 Dialog
  app/src/main/java/com/petpal/mungmate/model/Announcement.kt
  app/src/main/java/com/petpal/mungmate/model/ChatRoom.kt
  app/src/main/java/com/petpal/mungmate/model/FAQ.kt
  app/src/main/java/com/petpal/mungmate/model/Inquiry.kt
  app/src/main/java/com/petpal/mungmate/model/Message.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/ChatFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/ChatMessageAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/ChatRoomAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/ChatRoomFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chatting/ReportUserFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/AnnouncementAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/AnnouncementDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/AnnouncementFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/ContactUsFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/FAQAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/FAQFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/InquiryAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/InquiryFragment.kt
  app/src/main/res/drawable/expand_less_24px.xml
  app/src/main/res/drawable/expand_more_24px.xml
  app/src/main/res/drawable/home_24px.xml
  app/src/main/res/drawable/info_24px.xml
  app/src/main/res/drawable/search_24px.xml
  app/src/main/res/drawable/subdirectory_arrow_right_24px.xml
  app/src/main/res/layout/fragment_announcement.xml
  app/src/main/res/layout/fragment_announcement_detail.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_contact_us.xml
  app/src/main/res/layout/fragment_f_a_q.xml
  app/src/main/res/layout/fragment_inquiry.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_report_user.xml
  app/src/main/res/layout/row_announcement.xml
  app/src/main/res/layout/row_faq.xml
  app/src/main/res/layout/row_inquiry.xml
  app/src/main/res/menu/chat_room_menu.xml
  app/src/main/res/menu/faq_menu.xml
  app/src/main/res/navigation/chat.xml
  app/src/main/res/navigation/mypage.xml
Labels: ui

#19 산책 화면 / 사용자,방문지 bottom sheet, 필터 화면
  .idea/deploymentTargetDropDown.xml
  app/.idea/.gitignore
  app/.idea/gradle.xml
  app/.idea/misc.xml
  app/.idea/vcs.xml
  app/build.gradle
  app/libs/libDaumMapAndroid.jar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/MainFragment.kt
  app/src/main/java/com/petpal/mungmate/PlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/WalkFragment.kt
  app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  app/src/main/res/drawable/chip_shape.xml
  app/src/main/res/drawable/dog_home.png
  app/src/main/res/drawable/dog_walk.png
  app/src/main/res/drawable/favoirte_24px.xml
  app/src/main/res/drawable/menu_24px.xml
  app/src/main/res/drawable/restart_alt_24px.xml
  app/src/main/res/drawable/reviews_24px.xml
  app/src/main/res/drawable/stop_circle_24px.xml
  app/src/main/res/drawable/toggle_button_animated_background.xml
  app/src/main/res/drawable/toggle_shape_checked.xml
  app/src/main/res/drawable/toggle_shape_default.xml
  app/src/main/res/drawable/walk_bottom_sheet_background.xml
  app/src/main/res/drawable/walk_spinner_background.xml
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/fragment_place_review.xml
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/layout/row_walk_bottom_sheet_place.xml
  app/src/main/res/layout/row_walk_bottom_sheet_user.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/style.xml
Labels: ui

#26 feat : 커뮤니티 검색창 UI 만들기 #24
  app/src/main/java/com/petpal/mungmate/ui/community/CommunitySearchFragment.kt
  app/src/main/res/layout/fragment_community_search.xml
  app/src/main/res/navigation/community.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
Labels: feature, ui

#44 [#28] 필터 ui / 산책 on / off 아이콘 / 리뷰 화면 목록
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/PlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/res/layout/fragment_place_review.xml
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/layout/fragment_write_place_review.xml
  app/src/main/res/layout/row_place_review.xml
  app/src/main/res/layout/row_walk_bottom_sheet_place.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/walk.xml
Labels: ui

#48 feat: #41 내 정보 화면, 다른 사람 정보 화면
  app/src/main/java/com/petpal/mungmate/MyPageFragment.kt
  app/src/main/java/com/petpal/mungmate/model/Post.kt
  app/src/main/java/com/petpal/mungmate/ui/otheruser/OtherUserProfileFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/otheruser/PostAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/otheruser/PostDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/user/UserInfoFragment.kt
  app/src/main/res/drawable/chat_bubble_24px.xml
  app/src/main/res/drawable/circular_shape.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_other_user_profile.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/layout/row_pet_simple.xml
  app/src/main/res/layout/row_simple_post.xml
  app/src/main/res/menu/my_profile_menu.xml
  app/src/main/res/menu/other_user_profile_menu.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature, ui

#45 [#39]feat : 커뮤니티 검색 최근 검색 구현
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityRecentSearchesAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunitySearchFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunitySearchRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunitySearchViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/community/SearchesDao.kt
  app/src/main/java/com/petpal/mungmate/ui/community/SearchesDatabase.kt
  app/src/main/java/com/petpal/mungmate/ui/community/SearchesEntity.kt
  app/src/main/res/drawable/close.xml
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/fragment_community_search.xml
  app/src/main/res/layout/row_community_recent_searches.xml
  app/src/main/res/values/colors.xml
Labels: feature

#52 [#50]]bug : splash화면 바로 넘어가는 문제 해결
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/MainActivityViewModel.kt
Labels: bug

#60 반려견 등록 및 수정 화면
  app/src/main/java/com/petpal/mungmate/ManagePetFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/managepet/ManagePetFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/managepet/PetAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/managepet/PetUiState.kt
  app/src/main/java/com/petpal/mungmate/ui/managepet/PetUiStateDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/otheruser/OtherUserProfileFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/otheruser/PostAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/otheruser/PostDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/ui/otheruser/PostUiState.kt
  app/src/main/java/com/petpal/mungmate/ui/pet/AddPetFragment.kt
  app/src/main/java/com/petpal/mungmate/user/UserInfoFragment.kt
  app/src/main/res/layout/fragment_add_pet.xml
  app/src/main/res/layout/fragment_manage_pet.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/menu/complete_menu.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/navigation/manage_pet.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui

#63 build: firebase 연동, gitignore 추가
  .gitignore
  app/build.gradle
  app/google-services.json
  build.gradle
Labels: setting

#66 [#62] 채팅, 문의 ui 수정 + FAQ 필터링
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatMessageAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/FAQAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/FAQFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/customercenter/InquiryAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/orderhistory/OrderHistoryDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/orderhistory/OrderHistoryFragment.kt
  app/src/main/res/anim/fab_fade_in.xml
  app/src/main/res/anim/fab_fade_out.xml
  app/src/main/res/drawable/background_inquiry_status.xml
  app/src/main/res/drawable/background_unread_message_count.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_f_a_q.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_order_history.xml
  app/src/main/res/layout/fragment_order_history_detail.xml
  app/src/main/res/layout/fragment_walk_history.xml
  app/src/main/res/layout/fragment_walk_history_detail.xml
  app/src/main/res/layout/row_chat_date.xml
  app/src/main/res/layout/row_chat_receive_message.xml
  app/src/main/res/layout/row_chat_send_message.xml
  app/src/main/res/layout/row_chat_walk_mate_accept.xml
  app/src/main/res/layout/row_chat_walk_mate_reject.xml
  app/src/main/res/layout/row_chat_walk_mate_request.xml
  app/src/main/res/layout/row_inquiry.xml
  app/src/main/res/layout/row_order_history.xml
  app/src/main/res/menu/faq_menu.xml
Labels: feature, ui

#72 [#67] 산책 후기 화면 ui 작성
  app/src/main/java/com/petpal/mungmate/ui/walkreview/WalkReviewFragment.kt
  app/src/main/res/layout/fragment_walk_review.xml
  app/src/main/res/layout/row_match_history.xml
Labels: ui

#73 [#68,#70,#71]db에 카카오api로 받아온 방문지 + 리뷰 등록 / 등록된 리뷰/ 갯수 받아서 출력
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/model/KakaoPlaceResponse.kt
  app/src/main/java/com/petpal/mungmate/model/KakaoSearchResponse.kt
  app/src/main/java/com/petpal/mungmate/model/Review.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/KakaoApiService.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/api.kt
  app/src/main/jniLibs/.DS_Store
  app/src/main/res/drawable/call_24px.xml
  app/src/main/res/drawable/pace_24px.xml
  app/src/main/res/drawable/paw_pin.png
  app/src/main/res/drawable/petplace_pin.png
  app/src/main/res/layout/fragment_address_dialog.xml
  app/src/main/res/layout/fragment_delivery_point_manage.xml
  app/src/main/res/layout/fragment_detail_address.xml
  app/src/main/res/layout/fragment_place_review.xml
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/layout/fragment_write_place_review.xml
  app/src/main/res/layout/row_walk_bottom_sheet_place.xml
  app/src/main/res/layout/row_walk_bottom_sheet_user.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, ui, question

#74 [#65] fix : 커뮤니티 UI 개선, 커뮤니티 상세 페이지 UI 개선, 상품 등록 페이지 옵션 UI 개선, 바텀 네비게이션 애니메…
  app/src/main/java/com/petpal/mungmate/MainFragment.kt
  app/src/main/java/com/petpal/mungmate/ProductRegistrationFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailCommentAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/res/drawable/a11.jpg
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/fragment_product_registration.xml
  app/src/main/res/layout/row_community.xml
  app/src/main/res/layout/row_community_comment.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui

#75 feat: #61 자잘한 수정사항
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/MatchHistoryAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/MatchHistoryFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/MatchHistoryRecyclerAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/MatchHistoryUiState.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/MatchHistoryUiStateDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/PetFilterAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/PetFilterUiState.kt
  app/src/main/java/com/petpal/mungmate/ui/matchhistory/PetFilterUiStateDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/pet/AddPetFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walkhistory/WalkHistoryAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/walkhistory/WalkHistoryDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walkhistory/WalkHistoryFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walkhistory/WalkHistoryUiState.kt
  app/src/main/java/com/petpal/mungmate/ui/walkhistory/WalkHistoryUiStateDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/user/UserInfoFragment.kt
  app/src/main/res/layout/fragment_add_pet.xml
  app/src/main/res/layout/fragment_match_history.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_walk_history.xml
  app/src/main/res/layout/fragment_walk_history_detail.xml
  app/src/main/res/layout/row_match_history.xml
  app/src/main/res/layout/row_pet_simple.xml
  app/src/main/res/layout/row_walk_history_monthly.xml
  app/src/main/res/values/themes.xml
Labels: ui, fix

#77 [#76]feat : 커뮤니티 firebase firestore에 저장된 데이터 읽기,저장(일부 완료)
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/model/Post.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityWritingFragment.kt
  app/src/main/res/layout/row_community.xml
  app/src/main/res/values/strings.xml
Labels: feature

#82 [#83] 산책 후기 보내기, 받은 산책 후기 목록 ui
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/orderhistory/OrderHistoryFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walkreview/WalkReviewHistoryAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/walkreview/WalkReviewHistoryFragment.kt
  app/src/main/jniLibs/.DS_Store
  app/src/main/res/drawable/walk_review_rating_empty.png
  app/src/main/res/drawable/walk_review_rating_filled.png
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_order_history.xml
  app/src/main/res/layout/fragment_walk_review.xml
  app/src/main/res/layout/fragment_walk_review_history.xml
  app/src/main/res/layout/row_walk_review_history.xml
  app/src/main/res/navigation/nav_graph.xml
  settings.gradle
Labels: feature, ui

#81 [#76]feat : 커뮤니티 게시글 삭제 , 새로고침 구현
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/model/Post.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/row_community.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#80 [#79]fix : 바텀 네비게이션 애니메이션 진입 속도 나가는 속도 조절
  app/src/main/res/anim/from_left.xml
  app/src/main/res/anim/from_right.xml
  app/src/main/res/anim/to_left.xml
  app/src/main/res/anim/to_right.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: bug

#84 [ #76]feat : 커뮤니티 게시글 삭제 시 다이얼로그 구현
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
Labels: feature

#91 [#76]Feat : 커뮤니티 게시글 수정 기능 완료
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailModifyFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/res/menu/community_post_modify.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#93 78 구글 로그인, 카카오 로그인
  .firebaserc
  .gitignore
  app/build.gradle
  app/release/output-metadata.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/user/UserStartFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  firebase.json
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  gradle.properties
  settings.gradle
Labels: feature

#95 feat : 커뮤니티 게시글 등록할 때 이미지 firebase Storage에 저장하기#94
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/model/Post.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityWritingFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/EventPost.kt
  app/src/main/res/drawable/baseline_error_24.xml
Labels: feature

#101 Walkfragment 산책 off 시 place 관련 기능(commit 참고)
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/model/Favorite.kt
  app/src/main/java/com/petpal/mungmate/model/Place.kt
  app/src/main/java/com/petpal/mungmate/model/Review.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/managepet/ManagePetFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewViewRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
  app/src/main/java/com/petpal/mungmate/user/UserInfoFragment.kt
  app/src/main/java/com/petpal/mungmate/utils/LastKnownLocation.kt
  app/src/main/res/drawable/empty_heart.png
  app/src/main/res/drawable/filled_heart.png
  app/src/main/res/drawable/my_location_24px.xml
  app/src/main/res/drawable/photo.png
  app/src/main/res/layout/fragment_place_review.xml
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/layout/fragment_write_place_review.xml
  app/src/main/res/layout/row_walk_bottom_sheet_place.xml
  app/src/main/res/navigation/walk.xml
Labels: bug, feature, ui

#102 [#99]feat : 커뮤니티 게시글 이미지 한번 클릭하면 크게 볼 수 있고 확대기능, 댓글 기능
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/model/Post.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommentViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailCommentAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityWritingFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/FullScreenFragment.kt
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/fragment_community_writing.xml
  app/src/main/res/layout/fragment_full_screen.xml
  app/src/main/res/layout/row_community.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#103 78 feature login
  app/src/main/java/com/petpal/mungmate/FirebaseAuthExtensions.kt
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/model/PetData.kt
  app/src/main/java/com/petpal/mungmate/model/UserBasicInfo.kt
  app/src/main/java/com/petpal/mungmate/model/UserBasicInfoData.kt
  app/src/main/java/com/petpal/mungmate/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/pet/AddPetFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/user/UserInfoFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/user/UserStartFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/user/UserViewModel.kt
  app/src/main/java/com/petpal/mungmate/user/UserInfoFragment.kt
  app/src/main/res/layout/fragment_add_pet.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature, ui

#109 [#108]리뷰 수정,삭제, 관련ui
  app/src/main/java/com/petpal/mungmate/PlaceReviewModifyFragment.kt
  app/src/main/java/com/petpal/mungmate/model/Review.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewModifyFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/PlaceReviewViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
  app/src/main/res/layout/fragment_place_review_modify.xml
  app/src/main/res/layout/row_place_review.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#113 1:1 채팅 기능, 산책 메이트 요청
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/model/ChatRoom.kt
  app/src/main/java/com/petpal/mungmate/model/Match.kt
  app/src/main/java/com/petpal/mungmate/model/Message.kt
  app/src/main/java/com/petpal/mungmate/model/UserReport.kt
  app/src/main/java/com/petpal/mungmate/model/WalkReview.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatMessageAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/MessageAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ReportUserFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/TopMarginItemDecoration.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/WalkMateRequestFragment.kt
  app/src/main/res/drawable/background_receive_message.xml
  app/src/main/res/drawable/background_send_message.xml
  app/src/main/res/drawable/send_24px.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_report_user.xml
  app/src/main/res/layout/fragment_walk_history_detail.xml
  app/src/main/res/layout/fragment_walk_mate_request.xml
  app/src/main/res/layout/row_chat_receive_message.xml
  app/src/main/res/layout/row_chat_room.xml
  app/src/main/res/layout/row_chat_send_message.xml
  app/src/main/res/layout/row_chat_walk_mate_accept.xml
  app/src/main/res/layout/row_chat_walk_mate_request.xml
  app/src/main/res/navigation/chat.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
Labels: feature

#117 Image 처리, 저장
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/model/FirestoreUserBasicInfoData.kt
  app/src/main/java/com/petpal/mungmate/model/PetData.kt
  app/src/main/java/com/petpal/mungmate/model/UserBasicInfoData.kt
  app/src/main/java/com/petpal/mungmate/ui/pet/AddPetFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/user/UserInfoFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/user/UserStartFragment.kt
  app/src/main/java/com/petpal/mungmate/utils/FirebaseAuthExtensions.kt
  app/src/main/java/com/petpal/mungmate/utils/ImageUtils.kt
Labels: feature, ui

#125 [#124]fix : 자신이 등록한 게시물만 수정, 삭제가 가능
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
Labels: feature

#132 [ #130]fix : 커뮤니티 게시글 등록하고 뒤로 갈때 코루틴 처리 #130
  app/src/main/java/com/petpal/mungmate/ui/community/CommentViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailViewPager2Adapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunitySearchFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityWritingFragment.kt
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/item_community_view_pager2.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#129 [#118]산책하기 버튼 누르면 onWalk=true/location에 좌표 업로드 / 종료 누르면 onWalk=false로 업데이트 산책 종료 누르면 산책 리뷰 fragment에서 사진,리뷰 작성 후 db에 업로드 산책하기 버튼 누르면 onWalk=true 상태인 모든 사용자의 정보 받아오기 받아온 사용자의 위치정보와 내 위치정보를 비교해서 일정 거리(기본 2km) 이내에 있으면 마커 찍기 마커 누르면 사용자/반려동물 의 프로필 바텀시트에 표시
  app/src/main/java/com/petpal/mungmate/model/Pet.kt
  app/src/main/java/com/petpal/mungmate/model/ReceiveUser.kt
  app/src/main/java/com/petpal/mungmate/model/UserBasicInfoData.kt
  app/src/main/java/com/petpal/mungmate/model/WalkRecord.kt
  app/src/main/java/com/petpal/mungmate/ui/WalkReviewWriteFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
  app/src/main/java/com/petpal/mungmate/utils/onWalk.kt
  app/src/main/res/drawable/dog_area.png
  app/src/main/res/drawable/favorite_pin.png
  app/src/main/res/drawable/mylocation.png
  app/src/main/res/drawable/userlocation.png
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/layout/fragment_walk_history.xml
  app/src/main/res/layout/row_walk_bottom_sheet_user.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
Labels: feature, ui, question

#133 feat: #119 마커 주소 정보로 구글맵 place 이미지 받아오기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/MainActivity.kt
  app/src/main/java/com/petpal/mungmate/model/PlaceData.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/placereview/WritePlaceReviewViewRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/user/UserInfoFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
  build.gradle
Labels: feature

#136 [#135]feat : 마이페이지 DB에서 정보 가져오기
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/managepet/ManagePetFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/managepet/PetAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/managepet/PetUiState.kt
  app/src/main/java/com/petpal/mungmate/ui/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#138 [#137] 바텀 네비게이션으로 fragment 이동시 움직인 거리/ 시간 초기화 버그 수정 / 산책하기 시 dialog,카운트다운 /
  app/src/main/java/com/petpal/mungmate/MainFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/WalkReviewWriteFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
  app/src/main/java/com/petpal/mungmate/utils/onWalk.kt
  app/src/main/res/layout/fragment_walk.xml
Labels: feature, ui, fix

#141 [#135]feat :마이페이지 차단 관리
  app/src/main/java/com/petpal/mungmate/model/BlockUser.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/BlockStateDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/BlockUserRecyclerAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/ManageBlockFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/res/layout/row_block_user.xml
Labels: feature

#142 feat :커뮤니티 게시글 상세페이지 사진 뷰페이저2 연결 #131
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/ui/community/CommentViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailCommentAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailViewPager2Adapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/FullScreenFragment.kt
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/fragment_full_screen.xml
  app/src/main/res/layout/item_community_view_pager2.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#144 산책약속 받아와서 분기 후 혼자/같이 산책 -> 리뷰 분기 -> Review /WalkReview 분기 -> walkMate가 준 별점 평균 프로필 표시
  app/src/main/java/com/petpal/mungmate/model/Match.kt
  app/src/main/java/com/petpal/mungmate/model/ReceiveUser.kt
  app/src/main/java/com/petpal/mungmate/model/WalkReview.kt
  app/src/main/java/com/petpal/mungmate/ui/WalkReviewWriteFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
  app/src/main/res/layout/fragment_walk_review_write.xml
  app/src/main/res/layout/row_walk_bottom_sheet_user.xml
Labels: feature, ui

#140 [#115] 로그인 유저가 참여중인 채팅방 목록 필터링해서 표시 / 채팅 상대 프로필 & 반려견 정보 표시 / 매칭 상태에 따라 수락 거절 버튼 비활성화
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/model/Announcement.kt
  app/src/main/java/com/petpal/mungmate/model/ChatRoom.kt
  app/src/main/java/com/petpal/mungmate/model/FAQ.kt
  app/src/main/java/com/petpal/mungmate/model/FirestoreUserBasicInfoData.kt
  app/src/main/java/com/petpal/mungmate/model/Inquiry.kt
  app/src/main/java/com/petpal/mungmate/model/Item.kt
  app/src/main/java/com/petpal/mungmate/model/Match.kt
  app/src/main/java/com/petpal/mungmate/model/Message.kt
  app/src/main/java/com/petpal/mungmate/model/PetData.kt
  app/src/main/java/com/petpal/mungmate/model/UserReport.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/MessageAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ReportUserFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/WalkMateRequestFragment.kt
  app/src/main/res/drawable/background_receive_message.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/row_chat_receive_message.xml
  app/src/main/res/layout/row_chat_send_message.xml
  app/src/main/res/layout/row_chat_walk_mate_accept.xml
  app/src/main/res/layout/row_chat_walk_mate_reject.xml
  app/src/main/res/layout/row_chat_walk_mate_request.xml
  app/src/main/res/navigation/chat.xml
Labels: feature, fix

#151 마커 관련 수정/ 최근산책 로직 수정
  app/src/main/java/com/petpal/mungmate/model/WalkReview.kt
  app/src/main/java/com/petpal/mungmate/ui/WalkReviewWriteFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/res/drawable/location.png
  app/src/main/res/drawable/my_location.png
  app/src/main/res/drawable/mylocation.png
  app/src/main/res/drawable/paw.png
  app/src/main/res/drawable/pet_shop.png
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/layout/fragment_walk_review_write.xml
Labels: bug, feature, ui

#152 feat : 채팅방 차단 관리 실시간 반영
  app/src/main/java/com/petpal/mungmate/model/FirestoreUserBasicInfoData.kt
  app/src/main/java/com/petpal/mungmate/model/Message.kt
  app/src/main/java/com/petpal/mungmate/model/UserBasicInfoData.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/MessageAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/WalkMateRequestFragment.kt
  app/src/main/res/menu/chat_room_menu.xml
Labels: feature

#153 feat : 채팅 메시지 visible 분기 / match 생성 당시의 일시, 장소를 표시 / 산책 메이트 요청 송신측 메시지 타입 추가
  app/src/main/java/com/petpal/mungmate/model/ChatRoom.kt
  app/src/main/java/com/petpal/mungmate/model/Message.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/MessageAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/WalkMateRequestFragment.kt
  app/src/main/res/layout/row_chat_walk_mate_request_receive.xml
  app/src/main/res/layout/row_chat_walk_mate_request_send.xml
  app/src/main/res/navigation/chat.xml
Labels: feature, fix

#154 feat : 채팅방 목록 마지막 메시지, 시간 실시간 반영 / 시간 포맷 분기 / 시간 기준 내림차순 정렬
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRepository.kt
Labels: feature

#157 feat: 커뮤니티 ui다듬기
  app/build.gradle
  app/src/main/java/com/petpal/mungmate/MainFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityDetailCommentAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/community/CommunitySearchAdapter.kt
  app/src/main/res/drawable/comment.xml
  app/src/main/res/drawable/comment_20px.xml
  app/src/main/res/drawable/dog.png
  app/src/main/res/drawable/floor_lamp_20px.xml
  app/src/main/res/drawable/forum_20px.xml
  app/src/main/res/drawable/map_20px.xml
  app/src/main/res/drawable/more_vert.xml
  app/src/main/res/drawable/pet_supplies_20px.xml
  app/src/main/res/drawable/tag_20px.xml
  app/src/main/res/layout/fragment_community_post_detail.xml
  app/src/main/res/layout/row_community.xml
  app/src/main/res/layout/row_community_comment.xml
  app/src/main/res/navigation/fragment_nav_graph.xml
  app/src/main/res/raw/favorite.json
  app/src/main/res/values/strings.xml
Labels: ui

#162 버그수정 추후작성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/petpal/mungmate/services/TrackingService.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
Labels: bug, feature, fix

#164 fix : 프로필에서 새로운 채팅방 진입시 에러 해결
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRepository.kt
Labels: fix

#166 마커 클릭->차단목록에 추가 수정
  app/src/main/java/com/petpal/mungmate/model/Pet.kt
  app/src/main/java/com/petpal/mungmate/ui/WalkReviewWriteFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkViewModel.kt
  app/src/main/java/com/petpal/mungmate/utils/observeOnce.kt
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/layout/row_walk_bottom_sheet_user.xml
Labels: feature, fix

#168 필터 로직 수정 / 산책 시작->반투명 로직 수정/ 버그 픽스
  app/src/main/java/com/petpal/mungmate/BlockingDailogFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/res/layout/fragment_blocking_dailog.xml
  app/src/main/res/layout/fragment_walk.xml
Labels: feature, fix

#170 같이 산책하기 리뷰 관련 로직 수정
  app/src/main/java/com/petpal/mungmate/ui/WalkReviewWriteFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
Labels: feature, fix

#173 같이 산책 후 리뷰 분기 / 나이대 필터 / 버그 수정
  app/src/main/java/com/petpal/mungmate/BlockingDailogFragment.kt
  app/src/main/java/com/petpal/mungmate/model/WalkReviewForMate.kt
  app/src/main/java/com/petpal/mungmate/ui/WalkReviewWriteFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/res/layout/fragment_blocking_dailog.xml
  app/src/main/res/layout/fragment_walk.xml
Labels: feature, ui, fix

#174 fix : 산책 요청 거절시 Match 데이터 삭제 / 차단 관리 화면 에러 해결 / 채팅 & 차단관리 빈 리스트 경우 대체 레이아웃 표시
  app/src/main/java/com/petpal/mungmate/model/Match.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomRepository.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/ChatRoomViewModel.kt
  app/src/main/java/com/petpal/mungmate/ui/chat/MessageAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/BlockStateDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/BlockUserRecyclerAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/ManageBlockFragment.kt
  app/src/main/res/drawable/block_24px.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_manage_block.xml
Labels: fix

#176 feat : 마이페이지 차단관리 차단해제 기능 구현
  app/src/main/java/com/petpal/mungmate/model/BlockUser.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/BlockStateDiffCallback.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/BlockUserRecyclerAdapter.kt
  app/src/main/java/com/petpal/mungmate/ui/manageblock/ManageBlockFragment.kt
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_manage_block.xml
Labels: feature

#177 바텀 시트 유저 성별 표시/ 유저 성별/ 반려동물 성별,성향,중성화 여부 필터
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/res/layout/row_walk_bottom_sheet_user.xml
Labels: feature, ui

#178 같이 산책 리뷰 등록 완료 토스트 중복 수정 / 대화하기 -> 채팅창 갔다가 walkfragment 복귀시 내 위치 마커 양…
  app/src/main/java/com/petpal/mungmate/ui/WalkReviewWriteFragment.kt
  app/src/main/java/com/petpal/mungmate/ui/walk/WalkFragment.kt
  app/src/main/java/com/petpal/mungmate/utils/fragment123.kt
Labels: feature, fix
